kind: Pod
apiVersion: v1
metadata:
  name: go-kube-example-app
  labels:
    app: go-kube-example
spec:
  containers:
    - command:
        ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]
#        ["/gowalk"]
      image: localhost:5001/go-walk-delve:1.0
#      image: localhost:5001/go-walk:1.0
      name: go-kube-example-app
      imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: go-kube-example-service
spec:
  selector:
    app: go-kube-example
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: go-kube-example-service
                port:
                  number: 8080
---